### ISSUE TITLE
QA checks

### ISSUE THREAD

**Issue by Martin005** [tolgee/tolgee-platform#1546]
Even translators make mistakes, but some of these mistakes can be detected, and translators can be notified. No more mistakes like missing tags, missing parameters, or missing punctuation marks.

**Comment by JanCizmar** [comment]
- [ ] Check whether parameters in base are used in other translations

**Comment by jdimeo** [comment]
- [ ] Check that digits are present in the same order in the translation. If you are translating "John translated 10 strings in Tolgee" all translations with languages that use digits should be expected to have "10" in them. If the translator did "ten" the check could be suppressed, or you could encourage the translator to follow the example of the original and use digits.

**Comment by ZuzanaOdstrcilova** [comment]
@jdimeo Thank you for your idea. If you are interested, I would like to discuss it more:) - I sent you an email.

**Comment by ZuzanaOdstrcilova** [comment]
**Short specification of QA 1.0**
Figma Link for DEV:
https://www.figma.com/design/UYsyo57SCcWFpyMirhGmv4/Tasks-2025?node-id=10-14842&t=xZaJw19WPWNPChLa-1

**UI Views:**
- [ ] Dashboard view - show QA issues on each language row (plus dialog with types of QA issues and CTA buttons
- [ ] Translation view - icon QA issues, marking of the QA issue in the text, in the editor, QA check box on the right side, solving-ignoring of the issue, dialog for quick QA solving
- [ ] Filtering of QA issues
- [ ] Settings of QA

**Types of QA:**
- [ ] Empty translation
- [ ] Lenght issues
- [ ] Spaces mismatch
- [ ] Unmatches new lines
- [ ] Character case mismatch
- [ ] Missing numbers
- [ ]  Spelling
- [ ] Repeated words
- [ ] Punctuation mismatch
- [ ] Brackets mismatch
- [ ] Special character mismatch
- [ ] Different URLs
- [ ] Inconsistent placeholders
- [ ] Inconsistent HTML
- [ ] ICU syntax
- [ ] Unresolved comments
