### ISSUE TITLE
Visual editor & All format support

### ISSUE THREAD

**Issue by Martin005** [tolgee/tolgee-platform#1547]
## Visual editor
The current editor helps you with ICU syntax but doesn't help you with placeholders or HTML tags. For many, this is not an issue but it's problematic for example in the Arabic language, where it's hard to mix HTML and Arabic characters.

By visual editor, we mean a nice environment, where tags and parameter placeholders are represented visually, so translators don't have to worry about them. The plurals are also visually represented, so users can edit them without understanding the message formatting language.

- [ ] Rendering Markdown: #1298

## Formats support
Tolgee currently works fine with ICU message format and you can import data in .po format. However, there are many more formats we want to support. We would like to create a universal solution for format support, so we will be able to support any format in the future.

- [x] `.properties` file format: #1556 

### Required
 - User is able to to import data in any of these formats
   - [x] ICU
   - [x] .po (python, c, PHP)
   - [x] XLIFF
   - [x] iOS
   - [x] Android
   - [x] Flutter
   - [ ] i18next
   - [ ] Structured YAML
   - [x] .properties
 - We are able to export the data (with possible incompatibility warnings)
   - [x] ICU
   - [x] .po (python, c, PHP)
     - [ ] Let user choose to export base strings as keys (this might be required for plurals in some implementations)
   - [x] XLIFF
   - [x] iOS
   - [x] Android
   - [x] Flutter
   - [ ] i18next
   - [ ] Structured YAML
   - [x] .properties
  
 - [x] Translators edit text, not HTML or placeholders
 - [x] Users can edit placeholders and HTML tags
 - [x] Support for RTL languages
 - [x] It's backwards-compatible
   - [x] We are able to convert existing strings to the new format
   - [x] We are able to export the same data as before
 - [ ] Enable export of selected keys only  
### Optional
 - [x] User can decide placeholder format when exporting
 - [x] When importing and immediately exporting, user get the same data
 - [x] We don't have to migrate the data

## Plural support
Tolgee will store plurals in ICU message format. When importing from other formats, the string will be converted to ICU plurals. The inner of each plural form will be escaped, so it doesn't get interpreted and doesn't break ICU formatter. For such strings special plural editor with input for each form will be displayed. Nested or multiple plurals per key won't be supported for other than ICU strings. For ICU strings, single input with raw ICU string will be displayed.

## Universal ICU Placeholders
Tolgee will be able to convert specific parameters to it's native `Universal ICU Placeholders`. The syntax

{*param_name*, [*param_type*], [*param_style*]}

Supported conversions:

### {*param_name*}
- `%s` from Php and C/C++ `.po` files
- `%(param_name)s` from python `.po` files
- `%@` from Apple `.strings`, `.stringsdict`, `.xliff`

### {*param_name*, number}
- %d from Php and C/C++ `.po` files
- `%(param_name)d` from python `.po` files
- `%lld` from Apple `.strings`, `.stringsdict`, `.xliff`

### {*param_name*, number, scientific}
- %e from Php and C/C++ `.po` files
- `%(param_name)e` from python `.po` files
- `%e` from Apple `.strings`, `.stringsdict`, `.xliff`

### {*param_name*, number, 0.*precision zeros*}
- Precision zeros: `0` times the precision. e.g. : 0.00 for precision 2, for example php's "%0.3f" will be converted to {0, number, 0.00}
- Max precision is 50 otherwise parameter won't be converted 
- %0.*precision*f from Php and C/C++ `.po` files
- `%(param_name)0.*precision*f` from python `.po` files
- %0.*precision*f from Apple `.strings`, `.stringsdict`, `.xliff`

### Disabled Universal ICU Placeholders
To make Tolgee more convenient for users who work with native formats like `.po` or `.strings`, which use the c-like placeholders like `%s`, there will be option to disable Universal ICU placeholders. 

When ICU Universal Placeholders is disabled, the escaping will happen only for ICU format plural forms, otherwise, strings won't be escaped.

- [x] Add the `disable universal ICU placeholders` option to project settings

### Placeholder conversion on export
- [x] On export the parameters will be converted to matching parameter in specific format.

### Placeholder conversion on export
- [x] When importing user may choose to convert or not to convert the parameters to Universal ICU Placeholders.
- [x] If Universal ICU Placeholders are disabled on project level, it won't be converted and the option will be disabled

### Apple format specifics
Apple format does support different plural forms then ICU Message Format, while they declare, they follow Unicode standard. Since Tolgee will support only the ICU forms, the unsupported form from apple files will be discarded.
- [x] Document plural forms importing behaviour

### Import JSON and yaml
- [x] Enable array imports for JSON
- [ ]  Enable array imports for YAML

### Before finalization checklist
 - [x] Add links to the docs for the checkbox help buttons in the Import view
 - [x] Handle different plural forms for different languages when user changes existing language in the import endpoint (especially for .po, where it can be imported wrong, because of guessed language)
 - [x] Pass existing language tag to the file processors, so it can provide correct plural forms
 - [x] Test xcstrings plural variants for apple xliff 
 - [x] Fix errors when uploading multiple same files (constraint violations)
 - [x] Fix escaping in .po files when uploading data with icu characters in plurals
 
### Docs
- [x] Add other items to integrations item in platform docs and list all the SDKs and formats, so users can simply find them

**Comment by chogarcia** [comment]
any update on this? looks like https://github.com/tolgee/tolgee-js/issues/3077 is almost there

**Comment by JanCizmar** [comment]
> any update on this? looks like https://github.com/tolgee/tolgee-js/issues/3077 is almost there

The issue you're mentioning is not related to this. That issue mentions the ability to render Markdown on frontend. (Which we probably won't do now, since we don't want to over-engineer the package)

**Comment by CoenQian** [comment]
any update on this? Q4 is almost over.

**Comment by JanCizmar** [comment]
Hello @CoenQian, @chogarcia !

Sorry we're a bit delayed. But we have a deadline on February 16th. Please let me know if you're looking for a specific format, we will be supper happy for projects who would test our solution with different formats. :)

**Comment by JanCizmar** [comment]
Hello everyone! Unfortunately, we have to extend the deadline for this task by two weeks. We've encountered several issues due to the task's complexity and want to ensure a high-quality result. Also because future modifications could lead to breaking changes in the API and the behaviour of the import and export.

The new deadline is **1st March**. We apologize for any inconvenience.

**Comment by chogarcia** [comment]
wow thats awesome, looking forward to it!

what we are looking for is a text editor we can format (as markdown ideally) so we can parse it on the frontend to display long texts with paragraphs, bold, italic, titles, etc. Atm creating one key for each paragraph is been a nightmare.

**Comment by JanCizmar** [comment]
Update: Due to delays with last implementation details and writing documentation, we need to postpone the release day to **5th March**.

**Comment by JanCizmar** [comment]
Hey! We've released the major Visual Editor & Formats support on Tuesday 🎉. 

There are still some subtasks, we didn't finish in time, so I am converting it to separate issues.
 - i18next format support -> https://github.com/tolgee/tolgee-platform/issues/2159
 - Structured YAML (Ruby) Support -> https://github.com/tolgee/tolgee-platform/issues/2160
