### ISSUE TITLE
Slack integration final checklist

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2370]
I've took this from the new new feature checklist and added some custom points. Delete unnecesary points as you wish.
@huglx can you please final check this? Thanks!

### Implementation checklist
- [x] I've checked that all endpoints are well secured
- [x] The swagger documentation is OK including descriptions

## Before release checklist
- [x] @ZuzanaOdstrcilova checked the latest preview
- [x] Blog post about this new feature - @JanCizmar
- [x] Announcement in Tolgee App

## After release checklist
- [x] Roadmap is updated
- [x] We posted about this in social media 
  - [x] Twitter 
  - [x] Linkedin
  - [x] Facebook
  - [x] Reddit
  - [x] Slack Community
  - [x] Github Discussions
- [x] In App pricing is updated
- [x] Web pricing is updated
- [x] FAQ is updated
- [x] Website is updated

**Comment by JanCizmar** [comment]
@huglx, please consult the after release checklist with @stepan662 after it's released. Thanks. 👍🏻
