### ISSUE TITLE
🤩 Create simple Angular Todo list demo App

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2528]
![Hacktobefest 2024](https://github.com/user-attachments/assets/ac1bd9c1-fc1f-4375-9bf5-8e8c9b41cc15)

We are searching for beautiful demo creators

- [ ] Create a simple Angular demo app
  - So users can:
  - [ ] Create new todos
  - [ ] Remove todos
  - [ ] Edit todos
  - [ ] Translate all labels in the App with Tolgee
- [ ] Store it into `/demo` folder
- [ ] Add screenshot or video demo
- [ ] Write article about your demo on DEV.to

For more information and how to get your swag read the [Hacktoberfest.md](https://github.com/tolgee/tolgee-platform/blob/main/Hacktobefest2024.md)

In case of any questions, join our [Tolgee Slack Community](https://tolg.ee) to get help, share your ideas, suggestions, or questions and connect with other users and contributors.

**Comment by SGCODEX** [comment]
I want to work on this issue. Please assign it to me
