### ISSUE TITLE
🤩 Create Expense Tracker (Hacktoberfest Demo)

### ISSUE THREAD

**Issue by marketachalupnikova** [tolgee/tolgee-platform#2567]
![372383862-ac1bd9c1-fc1f-4375-9bf5-8e8c9b41cc15](https://github.com/user-attachments/assets/bedde4a2-8b96-4d73-af8c-ed008e42cb89)

We are searching for beautiful demo creators! For more information and how to get your swag, read the [Hacktoberfest.md](https://github.com/tolgee/tolgee-platform/blob/main/Hacktobefest2024.md)

## Demo: Expense Tracker 💰

Create an app that allows users to track their expenses. Users can input amounts, categories, and dates, and view their spending history.

### Technology Requirements
You can build this app using whatever framework you prefer: React, Angular, Vue, Next, Svelte, PHP, Flutter, Ruby, React native, iOS, or Android.

- [ ] Translate all labels in the App with Tolgee 
- [ ] Store the project into  [`/demos`](https://github.com/tolgee/tolgee-platform/tree/main/demos) folder  
- [ ] Add a screenshot or video demo to the PR
- [ ] Write a short article describing your demo app on DEV.to or your blog
- [ ] Please show your support and give a ⭐ to the Tolgee repository

If you have any questions, join our [Tolgee Slack Community](https://tolg.ee/) to get help, share your ideas, suggestions, or questions and connect with other users and contributors.

Thank you for participating in the Tolgee Hacktoberfest event! 🐁

**Comment by fadkeabhi** [comment]
I would like to contribute to this issue. Can you assign it to me.

**Comment by marketachalupnikova** [comment]
Sure, thanks a lot for your contributions! Happy coding @fadkeabhi

**Comment by Mayank77maruti** [comment]
Hey @marketachalupnikova , please assign this task.
I would love to complete this task.

**Comment by marketachalupnikova** [comment]
Thanks for your contribution @Mayank77maruti

**Comment by anshuman-rai-27** [comment]
Hey @marketachalupnikova , please assign this task.
