### ISSUE TITLE
Notifications core

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2577]
## Pre-specification
- [ ] We've setup responsible person
- [ ] We've checked how other tools solve the similar issues - @ZuzanaOdstrcilova 
- [ ] We've got users who require this feature and will pilot it and consult it (or we are the users) - Tolgee company itself

## Specification
- [ ] The user is able to see the bell in the top bar
- [ ] They can change notifications for each projects individually
- [ ] They can choose whether they want to be notified in app or via e-mail
- [ ] Notify users about
  - [ ] New task created
  - [ ] Task completed
  - [ ] Security stuff (password updated, MFA enabled)
  - [ ] Mentioned in translation comment  

## What's not in the scope
- [ ] Grouping - should be done on Activity Groups level
- [ ] Notifications about localization data edits (key / translation manipulation)
  -  Will be done with Activity Grouping / Activity improvements 

## UI Design Proposal
- [ ] @ZuzanaOdstrcilova can you please link here the design proposal

### The user stories are implemented
- [ ] ... Copy the stories from specification here ...

### Implementation checklist
- [ ] The code is well tested
  - [ ] User stories are covered by tests
    - [ ] Backend
    - [ ] e2e
  - [ ] ... Specify the test cases here, so you don't forget about important stuff ...
- [ ] I've checked that all endpoints are well secured
- [ ] The swagger documentation is OK including descriptions
- [ ] The documentation is updated
- [ ] Telemetry data is sent to PostHog

## Before release checklist
- [ ] Preview is created & user stories are tested on the preview 
- [ ] Blog post about this new feature
- [ ] Announcement in Tolgee App
- [ ] New keys are translated

## After release checklist
- [ ] Roadmap is updated
- [ ] We posted about this in social media
  - [ ] Twitter 
  - [ ] Linkedin
  - [ ] Facebook
  - [ ] Reddit
  - [ ] Slack Community
  - [ ] Github Discussions
- [ ] In App pricing is updated
- [ ] Web pricing is updated
- [ ] FAQ is updated
- [ ] Website is updated

**Comment by ZuzanaOdstrcilova** [comment]
Style of emails: 
https://github.com/tolgee/tolgee-platform/issues/2710
we can discuss it together

**Comment by ZuzanaOdstrcilova** [comment]
link to design of activity:
https://www.figma.com/design/wVmz098ZrSxswOI0nbIjQ2/Design-system-Tolgee?node-id=1504-18707&t=WDuUpTtIb4zSav5r-1
we can discuss it together :)
