### ISSUE TITLE
Fix big meta (context) storing logic

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#2771]
According to production data, the big meta data (context) has always has score 0 and the distance rows are never deleted. 

- [x] Compute average distance, instead of score
- [x] Remove distance entities with average distance higher then some value

**Tests**
- [x] Test many iterations of big meta saving
