### ISSUE TITLE
Batch Operations

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-platform#911]
- [x] Machine translation
- [x] Pre-translate by TM
- [x] Mark translations as "Reviewed", with language select
- [x] Mark translations as "Translated", with language select
- [x] Add tags on keys
- [x] Remove tags from keys
- [x] Change namespace of keys
- [x] Batch copy translations from one language to another languages
- [x] Delete keys
- [x] Clear translations – with language select

## Backend challenges
- [x] Large chunked processes using database and Redis
- [x] Use cache to save database resources
- [x] Handle Activity Log correctly (log start, finish and modified entities)
- [x] Handle single Chunk tasks (key deletion, tagging keys, state changes)
- [x] Enable Task cancellation 
- [x] Lock single job run in single project
- [ ] Optimize the queries
- [ ] Auto translation as a Batch Job

**Comment by ZuzanaOdstrcilova** [comment]
automated translating notification: https://www.figma.com/file/UCvcqHZe6owmJV5QolBMoj/tolgee-tasks?node-id=71%3A889

**Comment by ZuzanaOdstrcilova** [comment]
New more complex design: 
https://www.figma.com/file/UCvcqHZe6owmJV5QolBMoj/tolgee-tasks?node-id=1423-1585&t=gfvmt6BN2HEg2xUZ-0

**Comment by tiefenb** [comment]
Will this project also make possible to batch change the state of "reviewed"?

**Comment by JanCizmar** [comment]
Yep.
